### ISSUE TITLE
Making evaluation a separated package

### ISSUE THREAD

**Issue by mpariente** [fgnt/pb_bss#10]
Would you consider making `pb_bss.evaluation` a standalone python package?

**Comment by LukasDrude** [comment]
Dear Manuel,

we think that `pb_bss` is already a rather small package. We can offer to remove more of the dependencies in `setup.py`. Other than that, especially for multi-channel source separation/ extraction there might be more connection points where your repository may import from `pb_bss`.

What do you think?

Lukas

**Comment by mpariente** [comment]
Thanks for you quick answer Lukas !
I'll probably try to integrate it into asteroid, thanks

**Comment by mpariente** [comment]
Could you provide installation instruction please? Are there some know issues with Cython? I cannot compile the files

**Comment by boeddeker** [comment]
I will add some installation instructions.
We do not know a problem with Cython, but we haven't tested it on windows.
Could you tell me more about the error message?

**Comment by LukasDrude** [comment]
Dear Manuel,

following up with Christoph's answer, let us try to make it possible to import the metrics from `pb_bss`. We can definitely reduce dependencies from our side and, if needed, make it a PyPi package.

Lukas

**Comment by mpariente** [comment]
After installing numpy and Cython with pip, I run `pip install -e .` and it doesn't work (the stacktrace is huge, I can create another issue for it). 

After commenting out [these lines](https://github.com/fgnt/pb_bss/blob/master/setup.py#L28) in the setup.py, it works.
After that, I can uncomment the same lines and run `pip install -e .` again and this works (I can import the `_c*` function from extraction after that), it's a weird one !
