### ISSUE TITLE
How to setup or run your project?

### ISSUE THREAD

**Issue by zcy618** [fgnt/pb_bss#6]
hi dear author:
Could you give an instruction to show how to run your project please?
Thanks.

**Comment by LukasDrude** [comment]
Yes, we are kind of working on a small tutorial. We though of Jupyter notebooks to showcase the examples but are unsure about mixture files we can officially share. Would you like to share what you want to run first? Then we can prepare that example first.

**Comment by LukasDrude** [comment]
Dear @zcy618,

Christoph has now created a toy example here: https://github.com/fgnt/pb_bss/blob/master/examples/mixture_model_example.ipynb

You can run the notebook locally after installing this package with the following code:
```
git clone git@github.com:fgnt/pb_bss.git
cd pb_bss
pip install -e .
```

Let us know if you encounter any errors.
